name: Add Location of IP Addresses

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'  # 每隔两小时触发一次
  workflow_dispatch:  

permissions:
  contents: write

jobs:
  Modify_TXT:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install beautifulsoup4

    - name: Run Conversion Script
      run: python main.py  # 执行Python脚本进行IP地址转换

    - name: Commit Changes
      run: |
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Changes detected in the repository."
          git config core.ignorecase false
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes detected in the repository."
        fi
